In [1]:
import numpy as np

In [7]:
x = np.array([4,5,6])
print(x)
print(x.shape)   

# no of elements=3.  1 row, 3 columns
# it is a list

[4 5 6]
(3,)


In [8]:
y = np.array([[4],[5],[6]])
print(y)
print(y.shape) 

# 3 rows, 1 column
# it is a column vector

[[4]
 [5]
 [6]]
(3, 1)


In [9]:
#flatten this vector into a row vector

In [12]:
y = y.reshape((-1,))
print(y)
print(y.shape)

[4 5 6]
(3,)


In [11]:
#put -1 if we do not know the no. of elements

In [17]:
z = np.array([[4],[5],[6],[7]])
z = z.reshape((-1,2))
print(z)

[[4 5]
 [6 7]]


In [20]:
# Matrix is 2D array of scalars
# each matrix has m rows and n columns
# if m=n, then it is SQUARE MATRIX

In [21]:
# Tensor is array with more than 2 axes
# it is a generalised array with more than 2 axes

In [27]:
a = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
print(a)

print(a[1][2])

a[1:,:] = 9
print(a)

# 3*3 matrix

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[1 2 3]
 [9 9 9]
 [9 9 9]]


In [33]:
# T is tensor 

T = np.array( [ [[1,2,3],[4,5,6]] , [[7,8,9],[4,6,1]] ] )
print(T)
print(T.shape)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [4 6 1]]]
(2, 2, 3)


In [35]:
# Transpose of a matrix

In [41]:
print(a)
print(a.shape)

[[1 2 3]
 [9 9 9]
 [9 9 9]]
(3, 3)


In [44]:
at = np.transpose(a)
print(at)
print(at.shape)

[[1 9 9]
 [2 9 9]
 [3 9 9]]
(3, 3)


In [45]:
at.reshape((-1,))

array([1, 9, 9, 2, 9, 9, 3, 9, 9])

In [46]:
## Broadcasting

In [49]:
list = [1,2,3,4]

In [52]:
list = list + 1 #we cannot add any element to list

TypeError: can only concatenate list (not "int") to list

In [58]:
l = np.array(list)
l = l+1
print(l)

[2 3 4 5]


In [57]:
# Broadcasting is concept where numpy allows us to add any scalar to a vector

In [62]:
l = [ [1,2,3,4],[5,6,7,8] ]
l = np.array(l)
print(l)

l = l+1
print(l)

l = l**2
print(l)

[[1 2 3 4]
 [5 6 7 8]]
[[2 3 4 5]
 [6 7 8 9]]
[[ 4  9 16 25]
 [36 49 64 81]]


In [68]:
a = [ [1,2,3],[4,5,6] ]
b = [ [1,2],[3,4],[5,6] ]

print(a)
print(b)


[[1, 2, 3], [4, 5, 6]]
[[1, 2], [3, 4], [5, 6]]


In [69]:
a = np.array(a)
b = np.array(b)

print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [70]:
print(a.shape)
print(b.shape)

(2, 3)
(3, 2)


In [71]:
# Matrix Multiplication

In [73]:
prod = np.dot(a,b)
print(prod)

[[22 28]
 [49 64]]


In [74]:
# Element wise multiplication

In [80]:
a = [ [1,2,3],[4,5,6],[7,8,9] ]
print(a)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [76]:
y = np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
y = y*2 + 1
print(y)

[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]


In [81]:
print(a*y)

[[ 3.  2.  3.]
 [ 4. 15.  6.]
 [ 7.  8. 27.]]


In [82]:
# Norm of a Vector

In [83]:
# it is a measure of size of a vector   

In [84]:
x = np.array( [-5,3,10] )

In [86]:
#L2 norm
lp2 = np.linalg.norm(x)
print(lp2)

#here linag = linear algebra package which has pre definde fn norm()

11.575836902790225


In [89]:
lp1 = np.linalg.norm(x,ord=1) # default value of order = 2
print(lp1)

18.0


In [91]:
lpinf = np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0


In [94]:
r = np.array( [ [2,-2,1],[-1,2,-1],[2,-4,1] ] )
print(r)

[[ 2 -2  1]
 [-1  2 -1]
 [ 2 -4  1]]


In [95]:
l2_norm = np.linalg.norm(r,ord=2)
print(l2_norm)

5.9287221489704836
